server:
  port: 7070
  
  
  
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/kafkaconsumer
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
account-api:
  messages:
    AccountUpdated: Updated Successfully
    AccountNotUpdated: Unable to Update